volumes:
  qwenpaw-data:
    name: qwenpaw-data
  qwenpaw-secrets:
    name: qwenpaw-secrets
  qwenpaw-backups:
    name: qwenpaw-backups

services:
  qwenpaw:
    image: ghcr.io/yantianqi1/qwenpaw:latest
    container_name: qwenpaw
    pull_policy: always
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - QWENPAW_AUTH_ENABLED=true
    #   - QWENPAW_AUTH_USERNAME=admin
    #   - QWENPAW_AUTH_PASSWORD=yourpassword
    volumes:
      - qwenpaw-data:/app/working
      - qwenpaw-secrets:/app/working.secret
      - qwenpaw-backups:/app/working.backups
